/**
 * Calendar Service for SkillPath AI
 * Generates Google Calendar event links for study reminders.
 */

/**
 * Generates a Google Calendar event URL as a lightweight alternative to OAuth integration.
 */
export const generateCalendarUrl = ({ concept, date, time, nextStep, practiceTask, nextTopics }) => {
  const baseUrl = "https://www.google.com/calendar/render?action=TEMPLATE";
  
  // Create title
  const text = encodeURIComponent(`Study ${concept} with SkillPath AI`);
  
  // Format dates for Google Calendar (YYYYMMDDTHHMMSSZ)
  // Note: For simplicity and reliability in a web-link context, we'll use the user's selected date
  // and set a 1-hour duration.
  const startDateTime = new Date(`${date}T${time}`);
  const endDateTime = new Date(startDateTime.getTime() + 60 * 60 * 1000);
  
  const formatDate = (d) => d.toISOString().replace(/-|:|\.\d\d\d/g, "").replace("Z", "");
  const dates = `${formatDate(startDateTime)}/${formatDate(endDateTime)}`;
  
  // Create description with rich details
  const details = encodeURIComponent(
    `Mastering: ${concept}\n\n` +
    `🚀 Recommended Next Step: ${nextStep}\n` +
    `🛠 Practice Task: ${practiceTask}\n` +
    `📚 Next Topics to Explore: ${nextTopics.join(", ")}\n\n` +
    `Generated by SkillPath AI 🤖`
  );
  
  return `${baseUrl}&text=${text}&dates=${dates}&details=${details}`;
};

/**
 * Legacy mock for backward compatibility
 */
export const scheduleStudySession = async (concept, date) => {
  console.log(`Manual study session planned for ${concept} on ${date}`);
  return true;
};
